apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.airflow.prefix -}}airflow
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.frontend.rule: PathPrefixStrip
spec:
  rules:
    - http:
        paths:
          - path: {{ .Values.airflow.ingress.path.web }}
            backend:
              serviceName: {{ .Values.airflow.prefix -}}web
              servicePort: {{ .Values.airflow.prefix -}}pweb
      host: {{ .Values.airflow.ingress.host }}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.airflow.prefix -}}airflow-flower
  annotations:
    {{ range $key, $value := .Values.airflow.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  rules:
    - http:
        paths:
          - path: {{ .Values.airflow.ingress.path.flower }}
            backend:
              serviceName: {{ .Values.airflow.prefix -}}flower
              servicePort: {{ .Values.airflow.prefix -}}pflower
      host: {{ .Values.airflow.ingress.host }}
