airflow:
  prefix: ""
  fernet_key: ""
  service:
    type: ClusterIP
  baseUrl: "/"
  image: mumoshu/kube-airflow:1.8.0.0-1.6.1
  dag_path: /dags
  ingress:
    annotations:
    host:
    path:
      web: /airflow
      flower: /flower
  db:
    rabbitmq:
      user: airflow
      password: airflow
      basename: rabbitmq
      database: airflow
    postgres:
      user: airflow
      password: airflow
      basename: postgres
      database: airflow
  persistence:
    enabled: true
    ## If defined, volume.beta.kubernetes.io/storage-class: <storageClass>
    ## Default: volume.alpha.kubernetes.io/storage-class: default
    ##
    # storageClass:
    accessMode: ReadWriteOnce
    size: 1Gi
